name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t graph_service .

  smoke_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image (if not already built)
        run: docker build -t graph_service .

      - name: Run tests
        run: docker run graph_service ./smoke_test

  unit_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image (if not already built)
        run: docker build -t graph_service .

      - name: Run tests
        run: docker run graph_service ./unit_test

  integration_test:
    runs-on: ubuntu-latest
    needs: [build, unit_test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image (if not already built)
        run: docker build -t graph_service .

      - name: Run integration tests
        run: docker run graph_service ./integration_test

  debug:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image (if not already built)
        run: docker build -t graph_service .

      - name: Inspect Docker image contents
        run: docker run --rm graph_service ls -l /app

      - name: Check binary permissions
        run: docker run --rm graph_service ls -l /app/graph_service

      - name: Check for necessary shared libraries
        run: docker run --rm graph_service ldd /app/graph_service
