name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t graph_service .

  test:
    runs-on: ubuntu-latest
    needs: build  # Wait for 'lint' job to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image (if not already built)
        run: docker build -t graph_service .

      - name: Run tests
        run: docker run graph_service ./tests
