name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t graph_service .

      - name: Run unit tests
        run: docker run graph_service ./tests/unit

  lint:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code
        run: |
          # Example linting commands (adjust to your project's needs)
          docker run graph_service pylint .
          docker run graph_service flake8 .

  security_scan:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Security scanning
        run: |
          # Example security scanning commands (adjust to your project's needs)
          docker run graph_service bandit -r .

  # You can add more jobs for additional stages like integration tests, performance tests, etc.
