name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t graph_service .

      - name: Push Docker image to registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag graph_service ${{ secrets.DOCKER_REGISTRY }}/graph_service:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/graph_service:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: docker run graph_service ./tests

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/graph_service:latest
          namespace: default
          deployment: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: graph-service
            spec:
              replicas: 3
              selector:
                matchLabels:
                  app: graph-service
              template:
                metadata:
                  labels:
                    app: graph-service
                spec:
                  containers:
                    - name: graph-service
                      image: ${{ secrets.DOCKER_REGISTRY }}/graph_service:latest
                      ports:
                        - containerPort: 8080
